"""Build the strict, static-only Playtest precision-measurement queue.

Admission to this queue is deliberately narrower than admission to the
controlled export.  A row is emitted only when the version-isolated family
directory proves all of the following for the *same* candidate/mesh/PSA:

* the declared static candidate is complete in its exported REFSKELT;
* an exact TableHAnim-linked ``*_04_NOR`` PSA has full track-name coverage of
  that mesh; and
* every declared candidate bone is a track in that PSA.

The queue is an input to offline ActorX measurements only.  In particular it
does not choose a participant role, a contact target, an axis sign, a runtime
component, or generate any runtime rule.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Any


SCHEMA = "playtest-precision-measurement-queue-v1"
STATUS_SCHEMA = "playtest-family-evidence-status-v1"


class QueueError(ValueError):
    """Raised for evidence combinations that cannot enter the strict queue."""


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise QueueError(f"cannot read {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise QueueError("family evidence status must be a JSON object")
    return value


def _require_string(row: dict[str, Any], name: str, label: str) -> str:
    value = row.get(name)
    if not isinstance(value, str) or not value:
        raise QueueError(f"{label}: missing {name}")
    return value


def _runtime_requirements(family: dict[str, Any]) -> list[str]:
    """Retain only existing, unresolved runtime work; never infer a rule."""
    requirements = [
        item for item in family.get("unresolvedReasons", [])
        if isinstance(item, str) and item
    ]
    # The status format guarantees these are false.  Keeping them explicit in
    # every queue item protects consumers from mistaking an offline number for
    # a runtime result, even where the static source listed fewer unknowns.
    for item in (
        "runtime SkeletalMeshComponent binding",
        "reference/active participant and role confirmation",
        "primary target/component/bone and left-right ordering confirmation",
        "local-axis basis, sign, and calibration confirmation",
        "Viewer/runtime contact validation",
        "no runtime rule is generated by this queue or its measurements",
    ):
        if item not in requirements:
            requirements.append(item)
    return requirements


def build(status: dict[str, Any], status_path: Path) -> dict[str, Any]:
    if status.get("schema") != STATUS_SCHEMA or status.get("edition") != "playtest-ue5":
        raise QueueError("expected playtest-family-evidence-status-v1 for playtest-ue5")
    families = status.get("families")
    if not isinstance(families, list):
        raise QueueError("status families must be a list")

    queue: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for family in sorted(families, key=lambda value: str(value.get("hanimeId", "")).casefold()):
        if not isinstance(family, dict):
            raise QueueError("malformed family status row")
        family_id = _require_string(family, "hanimeId", "family")
        formal = family.get("formalStatus")
        if not isinstance(formal, dict):
            raise QueueError(f"{family_id}: missing formalStatus")
        if formal.get("state") != "precision_review_candidate_not_runtime_verified":
            continue
        if formal.get("runtimeVerified") or formal.get("runtimeRuleGenerated"):
            raise QueueError(f"{family_id}: a precision queue input must not be runtime verified/rule-generated")

        psa_by_operation = {
            item.get("operationKey"): item for item in family.get("normalPsa", [])
            if isinstance(item, dict) and isinstance(item.get("operationKey"), str)
        }
        mesh_by_id = {
            item.get("meshId"): item for item in family.get("controlledExport", {}).get("meshes", [])
            if isinstance(item, dict) and isinstance(item.get("meshId"), str)
        }
        emitted_for_family = 0
        for candidate_index, candidate_row in enumerate(family.get("staticCandidates", [])):
            if not isinstance(candidate_row, dict):
                raise QueueError(f"{family_id}: malformed static candidate")
            if candidate_row.get("precisionReviewStatus") != "eligible_for_precision_review_not_runtime_verified":
                continue
            candidate = candidate_row.get("declaredStaticCandidate")
            if not isinstance(candidate, dict) or not candidate.get("allBonesInExport"):
                raise QueueError(f"{family_id}: eligible candidate {candidate_index} lacks complete static REFSKELT evidence")
            axis = {
                "originBone": _require_string(candidate, "originBone", family_id),
                "directionBone": _require_string(candidate, "directionBone", family_id),
                "extendedTipBone": _require_string(candidate, "extendedTipBone", family_id),
                "supportBone": candidate.get("supportBone"),
                "topology": _require_string(candidate, "structure", family_id),
            }
            if axis["supportBone"] is not None and not isinstance(axis["supportBone"], str):
                raise QueueError(f"{family_id}: invalid supportBone")
            # Measurement works with topology terms that describe the static
            # hierarchy, not an inferred axis.  Current admitted families are
            # continuous chains or two-bone prop axes.
            if axis["topology"] == "continuous_chain":
                axis["topology"] = "continuous_parent_chain"
            elif axis["topology"] != "prop_axis":
                raise QueueError(f"{family_id}: unsupported admitted static topology {axis['topology']!r}")
            mesh_refs = candidate_row.get("candidateMeshRefs")
            operation_keys = candidate_row.get("fullCoverageNormalPsaOperationKeys")
            if not isinstance(mesh_refs, list) or len(mesh_refs) != 1 or not isinstance(mesh_refs[0], str):
                raise QueueError(f"{family_id}: candidate {candidate_index} must identify one exact mesh")
            if not isinstance(operation_keys, list) or not operation_keys:
                raise QueueError(f"{family_id}: candidate {candidate_index} has no exact full-coverage NORMAL PSA")
            mesh_ref = mesh_refs[0]
            mesh = mesh_by_id.get(mesh_ref)
            if not isinstance(mesh, dict) or mesh.get("auditStatus") != "audited_refskelt":
                raise QueueError(f"{family_id}: {mesh_ref} lacks an audited REFSKELT export")
            mesh_path = _require_string(mesh, "exportPath", family_id)
            source_mesh = _require_string(mesh, "sourceAsset", family_id)
            declared_bones = [axis["originBone"], axis["directionBone"], axis["extendedTipBone"]]
            if isinstance(axis["supportBone"], str):
                declared_bones.append(axis["supportBone"])
            bones = list(dict.fromkeys(declared_bones))
            for operation_key in operation_keys:
                psa = psa_by_operation.get(operation_key)
                if not isinstance(psa, dict):
                    raise QueueError(f"{family_id}: eligible candidate references missing PSA {operation_key!r}")
                coverage = [
                    item for item in psa.get("familyRefSkeletonCoverage", [])
                    if isinstance(item, dict) and item.get("meshRef") == mesh_ref and item.get("fullTrackNameCoverage") is True
                ]
                if len(coverage) != 1:
                    raise QueueError(f"{family_id}: {operation_key} is not exact full coverage for {mesh_ref}")
                # The directory's diagnostic is retained, but the queue has a
                # stronger requirement because these bones must be measured.
                if candidate_row.get("candidateBoneTrackPresence") != "all_declared_bones_present":
                    rejected.append({
                        "hanimeId": family_id, "candidateIndex": candidate_index,
                        "operationKey": operation_key,
                        "reason": "declared candidate bones are not all present as PSA tracks for frame-level measurement",
                    })
                    continue
                source_asset = _require_string(psa, "sourceAsset", family_id)
                psa_path = _require_string(psa, "exportPath", family_id)
                case_id = f"{family_id}--candidate-{candidate_index}--{hashlib.sha256(operation_key.encode('utf-8')).hexdigest()[:12]}"
                if case_id in seen_ids:
                    raise QueueError(f"duplicate measurement case id {case_id}")
                seen_ids.add(case_id)
                queue.append({
                    "id": case_id,
                    "edition": "playtest-ue5",
                    "hanimeId": family_id,
                    "candidateIndex": candidate_index,
                    "monsterDirectory": candidate_row.get("monsterDirectory"),
                    "manifest": "data/playtest-controlled-export-manifest-v1.json",
                    "operationKey": operation_key,
                    "sourceAsset": source_asset,
                    "sourceMesh": source_mesh,
                    "psaPath": psa_path,
                    "refSkeletonPath": mesh_path,
                    "bones": bones,
                    "axis": axis,
                    "staticCandidateScope": candidate.get("scope"),
                    "admissionEvidence": {
                        "formalStatus": formal.get("state"),
                        "candidateStatus": candidate_row.get("precisionReviewStatus"),
                        "candidateMeshRef": mesh_ref,
                        "fullCoverage": True,
                        "allDeclaredBonesPresentAsPsaTracks": True,
                        "normalPsaIntegrity": psa.get("integrity"),
                    },
                    "runtimeVerificationRequired": _runtime_requirements(family),
                    "formalRuleStatus": "measurement_only_not_runtime_verified_or_rule_generated",
                })
                emitted_for_family += 1
        if emitted_for_family == 0:
            rejected.append({"hanimeId": family_id, "reason": "precision candidate had no strictly measurable candidate/PSA pair"})

    state_counts = Counter(item.get("formalStatus", {}).get("state") for item in families if isinstance(item, dict))
    return {
        "schema": SCHEMA,
        "edition": "playtest-ue5",
        "policy": "A queue item is exact TableHAnim identity + declared static REFSKELT candidate + same-mesh full-coverage controlled NORMAL PSA + all candidate tracks. Measurements are static evidence only and never select a runtime target, role, axis calibration, component, or rule.",
        "source": {"path": str(status_path.resolve()), "sha256": sha256(status_path)},
        "coverage": {
            "sourceFamilyCount": len(families),
            "precisionReviewCandidateFamilyCount": state_counts["precision_review_candidate_not_runtime_verified"],
            "strictMeasurementCaseCount": len(queue),
            "strictMeasurementFamilyCount": len({item["hanimeId"] for item in queue}),
            "rejectedMeasurementPairCount": len(rejected),
            "runtimeVerifiedFamilyCount": 0,
            "runtimeRuleGeneratedFamilyCount": 0,
        },
        "cases": queue,
        "rejected": rejected,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--status", type=Path, default=Path("data/playtest-family-evidence-status-v1.json"))
    parser.add_argument("--output", type=Path, default=Path("data/playtest-precision-measurement-queue-v1.json"))
    args = parser.parse_args(argv)
    try:
        result = build(load(args.status), args.status)
    except QueueError as exc:
        parser.error(str(exc))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(args.output), **result["coverage"]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
