"""Generate the Lua-only, read-only precision-capture allowlist.

The capture path deliberately consumes the strict version-isolated queues rather
than a name heuristic.  It emits data only: enabling capture is a separate,
explicit runtime decision in ``precision_capture.lua``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCES = (
    ROOT / "data" / "demo-precision-review-queue-v1.json",
    ROOT / "data" / "playtest-precision-measurement-queue-v1.json",
)
DEFAULT_OUTPUT = ROOT / "fd_tcode_probe" / "Scripts" / "fd_tcode" / "data" / "precision_capture_data.lua"


def _lua_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _mesh_leaf(path: str) -> str:
    return str(path).replace("\\", "/").rstrip("/").split("/")[-1]


def _load_queue(path: Path) -> tuple[str, list[dict[str, Any]], str]:
    raw = path.read_bytes()
    payload = json.loads(raw.decode("utf-8"))
    edition = str(payload.get("edition") or "")
    cases = payload.get("cases")
    if not edition or not isinstance(cases, list):
        raise ValueError(f"{path}: expected edition and cases")
    return edition, cases, hashlib.sha256(raw).hexdigest()


def build(sources: tuple[Path, ...] = DEFAULT_SOURCES) -> str:
    editions: dict[str, list[dict[str, Any]]] = {}
    source_hashes: dict[str, str] = {}
    seen: set[tuple[str, str]] = set()
    for source in sources:
        edition, cases, digest = _load_queue(source)
        source_hashes[edition] = digest
        rows = editions.setdefault(edition, [])
        for case in cases:
            case_id = str(case.get("id") or "")
            hanime_id = str(case.get("hanimeId") or "")
            mesh = str(case.get("sourceMesh") or "")
            bones = case.get("bones")
            if not case_id or not hanime_id or not mesh or not isinstance(bones, list) or not bones:
                raise ValueError(f"{source}: malformed strict capture case {case_id or '<missing>'}")
            key = (edition, case_id)
            if key in seen:
                raise ValueError(f"duplicate strict capture case: {key}")
            seen.add(key)
            rows.append({
                "id": case_id,
                "hanimeId": hanime_id,
                "sourceMesh": mesh,
                "meshLeaf": _mesh_leaf(mesh),
                "bones": [str(bone) for bone in bones],
            })

    lines = [
        "-- Generated by tools/build_precision_capture_data.py; do not hand-edit.",
        "-- Static capture allowlist only. It never enables capture or a motion rule.",
        "return {",
        '  schema = "fd-precision-capture-data-v1",',
        "  source_queue_sha256 = {",
    ]
    for edition in sorted(source_hashes):
        lines.append(f"    [{_lua_quote(edition)}] = {_lua_quote(source_hashes[edition])},")
    lines.extend(["  },", "  editions = {"])
    for edition in sorted(editions):
        lines.append(f"    [{_lua_quote(edition)}] = {{")
        for row in sorted(editions[edition], key=lambda value: value["id"]):
            bones = ",".join(_lua_quote(bone) for bone in row["bones"])
            lines.append(
                "      { "
                f"id={_lua_quote(row['id'])}, "
                f"hanime_id={_lua_quote(row['hanimeId'])}, "
                f"source_mesh={_lua_quote(row['sourceMesh'])}, "
                f"mesh_leaf={_lua_quote(row['meshLeaf'])}, "
                f"bones={{{bones}}} "
                "},"
            )
        lines.append("    },")
    lines.extend(["  },", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output is not current")
    args = parser.parse_args()
    rendered = build()
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"precision capture data is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
