param(
    [string]$ExtractedRoot = "D:\zhifu\Desktop\data\mmd\extracted",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
$workspace = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $workspace "fd_tcode_probe\Scripts\fd_tcode\data\playtest_ue57_playable_hanime_identity_data.lua"
}

$tableBase = Join-Path $ExtractedRoot "Paralogue\Content\AS\Table\TableHAnim"
$tableFiles = @("$tableBase.uasset", "$tableBase.uexp")
foreach ($path in $tableFiles) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing extracted TableHAnim file: $path"
    }
}

function Lua-Quote([string]$Value) {
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Get-Category([string]$Family) {
    $text = $Family.ToLowerInvariant()
    $categories = [System.Collections.Generic.List[string]]::new()
    if ($text -match 'vaginal|vagina') { $categories.Add('vaginal') }
    if ($text -match 'anal|anus') { $categories.Add('anal') }
    if ($text -match 'mouth|oral') { $categories.Add('mouth') }
    if ($text -match 'hand') { $categories.Add('hand') }
    if ($text -match 'foot') { $categories.Add('foot') }
    if ($text -match 'breast') { $categories.Add('breast') }
    if ($text -match 'thigh') { $categories.Add('thigh') }
    if ($categories.Count -eq 1) { return $categories[0] }
    if ($categories.Count -eq 0 -and $text -match 'sex|dildo') { return 'sex' }
    return 'other'
}

$strings = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($path in $tableFiles) {
    foreach ($value in (& rg -a -o -N '[A-Za-z][A-Za-z0-9_]{3,}' $path)) {
        [void]$strings.Add($value)
    }
}
$montages = @($strings | Where-Object { $_ -match '(?i)_Montage' } | Sort-Object)

# Each row has at least one playable humanoid-participant Montage.  Keep this
# list in sync with the roles supported by the Playtest probe, including the
# spelling aliases emitted by different TableHAnim revisions.  Its suffix gives
# the exact family boundary without deserializing unversioned properties.
$playableHumanoidOwners = @(
    'Ada', 'Alet', 'Anya', 'Erika',
    'Gala', 'Galatea',
    'Talon', 'Celia', 'Ceila', 'Elizabeth',
    'Juzi', 'Juzhi', 'Yanshi'
)
$playableOwnerPattern = '(?i)_(' + (($playableHumanoidOwners | ForEach-Object { [regex]::Escape($_) }) -join '|') + ')_01$'
$families = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
foreach ($asset in $montages) {
    $stem = $asset -replace '(?i)_Montage.*$', ''
    if ($stem -match $playableOwnerPattern) {
        [void]$families.Add($stem.Substring(0, $stem.Length - $matches[0].Length))
    }
}

$familyAssets = @{}
$familyTags = @{}
foreach ($family in $families) {
    $familyAssets[$family] = [System.Collections.Generic.List[string]]::new()
    $familyTags[$family] = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
}
foreach ($asset in $montages) {
    $stem = $asset -replace '(?i)_Montage.*$', ''
    foreach ($family in $families) {
        $prefix = $family + '_'
        if ($stem.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
            $familyAssets[$family].Add($asset)
            [void]$familyTags[$family].Add($stem.Substring($prefix.Length))
            break
        }
    }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('-- Generated by tools/build_ue57_playable_hanime_identity_data.ps1.')
$lines.Add('-- Source: exact names from the extracted UE 5.7 Playtest TableHAnim NameMap.')
$lines.Add('local Catalog = { by_montage = {}, by_family = {} }')
$lines.Add('')
$lines.Add('local function normalized(value)')
$lines.Add('    return string.lower(tostring(value or "")):gsub("[^%w]", "")')
$lines.Add('end')
$lines.Add('')
$lines.Add('local function add_asset(family, category, participant_tag, asset)')
$lines.Add('    local lower = string.lower(asset)')
$lines.Add('    local phase = string.find(lower, "_max", 1, true) and "max"')
$lines.Add('        or (string.find(lower, "_min", 1, true) and "min")')
$lines.Add('        or "normal"')
$lines.Add('    Catalog.by_montage[normalized(asset)] = {')
$lines.Add('        asset = asset, asset_paths = {}, category = category,')
$lines.Add('        catalog_refs = { "Playtest/UE5.7/TableHAnim-NameMap" },')
$lines.Add('        evidence = "ue57_exact_table_hanim_namemap", hanime_id = family,')
$lines.Add('        participant_tag = participant_tag, phase = phase,')
$lines.Add('    }')
$lines.Add('end')
$lines.Add('')

foreach ($family in ($families | Sort-Object)) {
    $category = Get-Category $family
    $tags = @($familyTags[$family] | Sort-Object)
    $lines.Add('Catalog.by_family[' + (Lua-Quote $family) + '] = {')
    $lines.Add('    hanime_id = ' + (Lua-Quote $family) + ', category = ' + (Lua-Quote $category) + ',')
    $lines.Add('    catalog_refs = { "Playtest/UE5.7/TableHAnim-NameMap" },')
    $lines.Add('    participant_tags = {')
    foreach ($tag in $tags) { $lines.Add('        ' + (Lua-Quote $tag) + ',') }
    $lines.Add('    },')
    $lines.Add('}')
    foreach ($asset in ($familyAssets[$family] | Sort-Object -Unique)) {
        $stem = $asset -replace '(?i)_Montage.*$', ''
        $tag = $stem.Substring($family.Length + 1)
        $lines.Add('add_asset(' + (Lua-Quote $family) + ', ' + (Lua-Quote $category) + ', ' + (Lua-Quote $tag) + ', ' + (Lua-Quote $asset) + ')')
    }
    $lines.Add('')
}
$lines.Add('return Catalog')

$parent = Split-Path -Parent $OutputPath
[System.IO.Directory]::CreateDirectory($parent) | Out-Null
[System.IO.File]::WriteAllLines($OutputPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $($families.Count) UE5.7 families and $((@($familyAssets.Values | ForEach-Object { $_.Count }) | Measure-Object -Sum).Sum) exact Montage aliases: $OutputPath"
