"""Adapt static F/F semantic entries into a UE4SS-readable sidecar table.

The sidecar is merged by ProfileStore after the legacy profile table.  Entries
are formal static records, but have neither geometry nor calibration and are
therefore not eligible for automatic device-driving paths.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "playtest-female-female-provisional-contact-catalog-v1.json"
OUTPUT = ROOT / "fd_tcode_probe" / "Scripts" / "fd_tcode" / "data" / "female_female_provisional_profile_data.lua"


def lua_value(value: Any, indent: int = 0) -> str:
    prefix, child = " " * indent, " " * (indent + 4)
    if value is None: return "nil"
    if isinstance(value, str): return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool): return "true" if value else "false"
    if isinstance(value, (int, float)): return str(value)
    if isinstance(value, list):
        return "{}" if not value else "{\n" + "\n".join(child + lua_value(x, indent + 4) + "," for x in value) + "\n" + prefix + "}"
    if isinstance(value, dict):
        return "{}" if not value else "{\n" + "\n".join(child + f"[{json.dumps(str(k), ensure_ascii=False)}] = " + lua_value(v, indent + 4) + "," for k, v in value.items()) + "\n" + prefix + "}"
    raise TypeError(type(value))


def build(source: Path = SOURCE) -> dict[str, Any]:
    payload = json.loads(source.read_text(encoding="utf-8"))
    families = payload.get("families")
    if payload.get("edition") != "playtest-ue5" or not isinstance(families, list):
        raise ValueError("expected Playtest F/F provisional catalog")
    profiles: dict[str, Any] = {}
    for family in families:
        identity = family["identityEvidence"]
        participants = family["participants"]
        hanime_id = family["hanimeId"]
        if len(participants) != 2 or not identity.get("exactMontagePackagePaths"):
            raise ValueError(f"{hanime_id}: incomplete static proof")
        profiles[hanime_id] = {
            "id": hanime_id,
            "match_keys": [hanime_id, *identity["tableHAnimImportedAssets"]],
            "category": family["category"],
            "roles": {"primary": participants[0]["skeletonCatalog"], "partner": participants[1]["skeletonCatalog"]},
            "status": "static_formal_pending_runtime_calibration",
            "disabledForAutomaticDeviceOutput": False,
            "runtimeCalibrationPending": True,
            "staticEvidence": {
                "edition": "playtest-ue5",
                "tableHAnimReferences": identity["tableHAnimReferences"],
                "exactMontagePackagePaths": identity["exactMontagePackagePaths"],
                "identityIndexCrossCheck": "match",
            },
            "semanticContactCandidates": [p["candidateContactPoints"] for p in participants],
            "runtimeSelection": {"reference": None, "target": None, "primarySecondaryOrdering": "not_selected"},
        }
    return {"schema_version": 1, "revision": "playtest-ff-static-formal-v1", "profile_count": len(profiles), "device_output": "disabled", "profiles": profiles}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    doc = build()
    args.output.write_text("-- Generated by tools/build_playtest_ff_runtime_adapter.py; static formal profiles only.\nreturn " + lua_value(doc) + "\n", encoding="utf-8")
    return 0

if __name__ == "__main__": raise SystemExit(main())
