from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_demo_static_bone_runtime_adapter import OUTPUT, build, lua_value


class DemoStaticBoneRuntimeAdapterTests(unittest.TestCase):
    def test_all_demo_static_formal_profiles_are_game_side_readable(self) -> None:
        document = build()
        self.assertEqual(document["schema_version"], 1)
        self.assertEqual(document["profile_count"], 145)
        self.assertEqual(len(document["profiles"]), 145)
        for profile in document["profiles"].values():
            self.assertEqual(profile["edition"], "demo-ue4.25")
            self.assertEqual(profile["exactHanimeId"], profile["id"])
            self.assertIn(profile["exactHanimeId"], profile["match_keys"])
            self.assertEqual(profile["status"], "static_formal_pending_runtime_calibration")
            self.assertFalse(profile["disabledForAutomaticDeviceOutput"])
            self.assertTrue(profile["runtimeCalibrationPending"])
            self.assertIn("participants", profile)
            self.assertIn("referenceCandidates", profile)
            self.assertIn("targetCandidates", profile)
            self.assertNotIn("geometry", profile)

        hound_profiles = [profile for profile in document["profiles"].values() if "Hound" in profile["participants"]]
        self.assertEqual(len(hound_profiles), 26)
        tail_profiles = [profile for profile in hound_profiles if profile["id"] != "AletHound_Mouth01"]
        self.assertEqual(len(tail_profiles), 25)
        for profile in tail_profiles:
            self.assertEqual(profile["referenceCandidates"][0]["id"], "hound-nonmouth-tail")
            self.assertEqual(profile["referenceCandidates"][0]["originBone"], "Tail0_M")

    def test_sidecar_is_current_and_store_has_edition_isolated_non_overwriting_merge(self) -> None:
        expected = "-- Generated by tools/build_demo_static_bone_runtime_adapter.py; Demo static formal profiles only.\nreturn " + lua_value(build()) + "\n"
        self.assertEqual(OUTPUT.read_text(encoding="utf-8"), expected)
        store = Path("fd_tcode_probe/Scripts/fd_tcode/core/profile_store.lua").read_text(encoding="utf-8")
        config = Path("fd_tcode_probe/Scripts/fd_tcode/config.lua").read_text(encoding="utf-8")
        readme = Path("fd_tcode_probe/README.md").read_text(encoding="utf-8")
        self.assertIn('FD_TCODE_GAME_EDITION', store)
        self.assertIn('"demo-ue4.25"', store)
        self.assertIn('"playtest-ue5"', store)
        self.assertIn('"demo_static_formal_profile_data.lua"', store)
        self.assertIn('"female_female_provisional_profile_data.lua"', store)
        self.assertIn('"nonhuman_static_formal_profile_data.lua"', store)
        self.assertIn('existing.status ~= "enabled_for_simulation_validation"', store)
        self.assertIn('profile_edition ~= sidecar_spec.edition', store)
        self.assertIn('static formal sidecars skipped', store)
        self.assertIn('FD_TCODE_GAME_EDITION', config)
        self.assertIn('FD_TCODE_GAME_EDITION', readme)
        self.assertIn('no static-formal sidecar', readme)


if __name__ == "__main__":
    unittest.main()
