from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_playtest_nonhuman_runtime_adapter import OUTPUT, build, profiles_for_edition


class PlaytestNonhumanRuntimeAdapterTests(unittest.TestCase):
    def test_all_227_static_formal_profiles_are_game_readable(self) -> None:
        document = build()
        self.assertEqual(document["schema_version"], 1)
        self.assertEqual(document["edition"], "playtest-ue5")
        self.assertEqual(document["profile_count"], 227)
        self.assertEqual(len(document["profiles"]), 227)
        for profile in document["profiles"].values():
            self.assertEqual(profile["edition"], "playtest-ue5")
            self.assertEqual(profile["exactHanimeId"], profile["id"])
            self.assertIn(profile["exactHanimeId"], profile["match_keys"])
            self.assertEqual(profile["status"], "static_formal_pending_runtime_calibration")
            self.assertFalse(profile["disabledForAutomaticDeviceOutput"])
            self.assertTrue(profile["runtimeCalibrationPending"])
            self.assertIn("reference", profile["participants"])
            self.assertIn("target", profile["participants"])
            self.assertIn("targetCandidates", profile)
            self.assertNotIn("geometry", profile)
        def depth(value: object) -> int:
            if not isinstance(value, (dict, list)):
                return 0
            children = value.values() if isinstance(value, dict) else value
            return 1 + max((depth(item) for item in children), default=0)
        # ProfileStore refuses tables deeper than 16 levels.
        self.assertLessEqual(depth(document), 16)

    def test_edition_gate_isolated_from_demo_even_when_hanime_ids_overlap(self) -> None:
        document = build()
        self.assertEqual(len(profiles_for_edition(document, "playtest-ue5")), 227)
        self.assertEqual(profiles_for_edition(document, "demo-ue4.25"), {})

    def test_checked_in_sidecar_is_current_and_uses_the_common_sidecar_schema(self) -> None:
        expected = "-- Generated by tools/build_playtest_nonhuman_runtime_adapter.py; static formal profiles only.\nreturn "
        from build_playtest_nonhuman_runtime_adapter import lua_value
        self.assertEqual(OUTPUT.read_text(encoding="utf-8"), expected + lua_value(build()) + "\n")
        sidecar = OUTPUT.read_text(encoding="utf-8")
        self.assertIn('["schema_version"] = 1', sidecar)
        self.assertIn('["profiles"] = {', sidecar)


if __name__ == "__main__":
    unittest.main()
