-- Generated by tools/build_pose_catalog.py. Runtime data only; no Unreal calls.
return {
    ["schema_version"] = 1,
    ["revision"] = "pose-catalog-v2-102",
    ["profile_count"] = 102,
    ["device_output"] = "disabled",
    ["profiles"] = {
        ["AletAnya_Sex01"] = {
            ["id"] = "AletAnya_Sex01",
            ["match_keys"] = {
                "AletAnya_Sex01",
                "AletAnya_Sex01_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Anya",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "anya-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletAnya_Sex02"] = {
            ["id"] = "AletAnya_Sex02",
            ["match_keys"] = {
                "AletAnya_Sex02",
                "AletAnya_Sex02_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Anya",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "anya-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletAnya_Sex03"] = {
            ["id"] = "AletAnya_Sex03",
            ["match_keys"] = {
                "AletAnya_Sex03",
                "AletAnya_Sex03_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Anya",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "anya-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletAnya_Sex05"] = {
            ["id"] = "AletAnya_Sex05",
            ["match_keys"] = {
                "AletAnya_Sex05",
                "AletAnya_Sex05_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Anya",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "anya-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletByakhee_Foot01"] = {
            ["id"] = "AletByakhee_Foot01",
            ["match_keys"] = {
                "AletByakhee_Foot01",
                "AletByakhee_Foot01_Alet_04_nor",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Byakhee",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletByakhee_Vaginal01"] = {
            ["id"] = "AletByakhee_Vaginal01",
            ["match_keys"] = {
                "AletByakhee_Vaginal01",
                "AletByakhee_Vaginal01_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Byakhee",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepOne_Anal01"] = {
            ["id"] = "AletDeepOne_Anal01",
            ["match_keys"] = {
                "AletDeepOne_Anal01",
                "AletDeepOne_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "DeepOne",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Anal02"] = {
            ["id"] = "AletDeepone_Anal02",
            ["match_keys"] = {
                "AletDeepone_Anal02",
                "AletDeepone_Anal02_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepOne_Hand01"] = {
            ["id"] = "AletDeepOne_Hand01",
            ["match_keys"] = {
                "AletDeepOne_Hand01",
                "AletDeepOne_Hand01_Alet_04_NOR",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "DeepOne",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepOne_Mouth01"] = {
            ["id"] = "AletDeepOne_Mouth01",
            ["match_keys"] = {
                "AletDeepOne_Mouth01",
                "AletDeepOne_Mouth01_Alet_04_NOR",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "DeepOne",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Vagina02"] = {
            ["id"] = "AletDeepone_Vagina02",
            ["match_keys"] = {
                "AletDeepone_Vagina02",
                "AletDeepone_Vagina02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Vagina03"] = {
            ["id"] = "AletDeepone_Vagina03",
            ["match_keys"] = {
                "AletDeepone_Vagina03",
                "AletDeepone_Vagina03_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Vagina06"] = {
            ["id"] = "AletDeepone_Vagina06",
            ["match_keys"] = {
                "AletDeepone_Vagina06",
                "AletDeepone_Vagina06_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Vaginal01"] = {
            ["id"] = "AletDeepone_Vaginal01",
            ["match_keys"] = {
                "AletDeepone_Vaginal01",
                "AletDeepone_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Vaginal04"] = {
            ["id"] = "AletDeepone_Vaginal04",
            ["match_keys"] = {
                "AletDeepone_Vaginal04",
                "AletDeepone_Vaginal04_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDeepone_Vaginal05"] = {
            ["id"] = "AletDeepone_Vaginal05",
            ["match_keys"] = {
                "AletDeepone_Vaginal05",
                "AletDeepone_Vaginal05_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Deepone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDreamer_Vaginal18"] = {
            ["id"] = "AletDreamer_Vaginal18",
            ["match_keys"] = {
                "AletDreamer_Vaginal18",
                "AletDreamer_Vaginal18_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Dreamer",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDrone_Anal01"] = {
            ["id"] = "AletDrone_Anal01",
            ["match_keys"] = {
                "AletDrone_Anal01",
                "AletDrone_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Drone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDrone_Vaginal01"] = {
            ["id"] = "AletDrone_Vaginal01",
            ["match_keys"] = {
                "AletDrone_Vaginal01",
                "AletDrone_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Drone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletDrone_Vaginal02"] = {
            ["id"] = "AletDrone_Vaginal02",
            ["match_keys"] = {
                "AletDrone_Vaginal02",
                "AletDrone_Vaginal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Drone",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletErika_DoubleDildo01"] = {
            ["id"] = "AletErika_DoubleDildo01",
            ["match_keys"] = {
                "AletErika_DoubleDildo01",
                "AletErika_DoubleDildo01_Alet_04_NOR",
            },
            ["category"] = "prop_guided",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErika_DoubleDildo02"] = {
            ["id"] = "AletErika_DoubleDildo02",
            ["match_keys"] = {
                "AletErika_DoubleDildo02",
                "AletErika_DoubleDildo02_Alet_04_nor",
            },
            ["category"] = "prop_guided",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErika_Sex01"] = {
            ["id"] = "AletErika_Sex01",
            ["match_keys"] = {
                "AletErika_Sex01",
                "AletErika_Sex01_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErika_Sex02"] = {
            ["id"] = "AletErika_Sex02",
            ["match_keys"] = {
                "AletErika_Sex02",
                "AletErika_Sex02_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErika_Sex03"] = {
            ["id"] = "AletErika_Sex03",
            ["match_keys"] = {
                "AletErika_Sex03",
                "AletErika_Sex03_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErika_Sex05"] = {
            ["id"] = "AletErika_Sex05",
            ["match_keys"] = {
                "AletErika_Sex05",
                "AletErika_Sex05_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErika_Sex06"] = {
            ["id"] = "AletErika_Sex06",
            ["match_keys"] = {
                "AletErika_Sex06",
                "AletErika_Sex06_Alet_04_NOR",
            },
            ["category"] = "generic_pair",
            ["participant_hint"] = "Erika",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletErikaDoubleDildo_JMLesbian03"] = {
            ["id"] = "AletErikaDoubleDildo_JMLesbian03",
            ["match_keys"] = {
                "AletErikaDoubleDildo_JMLesbian03",
                "AletErikaDoubleDildo_JMLesbian03_Alet_04_NOR",
            },
            ["category"] = "prop_guided",
            ["participant_hint"] = "ErikaDoubleDildo_JMLesbian03",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "erika-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["AletGhast_Hand01"] = {
            ["id"] = "AletGhast_Hand01",
            ["match_keys"] = {
                "AletGhast_Hand01",
                "AletGhast_Hand01_Alet_04_nor",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "Ghast",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Anal01"] = {
            ["id"] = "AletHound_Anal01",
            ["match_keys"] = {
                "AletHound_Anal01",
                "AletHound_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Anal02"] = {
            ["id"] = "AletHound_Anal02",
            ["match_keys"] = {
                "AletHound_Anal02",
                "AletHound_Anal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Hand01"] = {
            ["id"] = "AletHound_Hand01",
            ["match_keys"] = {
                "AletHound_Hand01",
                "AletHound_Hand01_Alet_04_nor",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Mouth01"] = {
            ["id"] = "AletHound_Mouth01",
            ["match_keys"] = {
                "AletHound_Mouth01",
                "AletHound_Mouth01_Alet_04_NOR",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Vaginal01"] = {
            ["id"] = "AletHound_Vaginal01",
            ["match_keys"] = {
                "AletHound_Vaginal01",
                "AletHound_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Vaginal02"] = {
            ["id"] = "AletHound_Vaginal02",
            ["match_keys"] = {
                "AletHound_Vaginal02",
                "AletHound_Vaginal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Vaginal03"] = {
            ["id"] = "AletHound_Vaginal03",
            ["match_keys"] = {
                "AletHound_Vaginal03",
                "AletHound_Vaginal03_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Vaginal04"] = {
            ["id"] = "AletHound_Vaginal04",
            ["match_keys"] = {
                "AletHound_Vaginal04",
                "AletHound_Vaginal04_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletHound_Vaginal05"] = {
            ["id"] = "AletHound_Vaginal05",
            ["match_keys"] = {
                "AletHound_Vaginal05",
                "AletHound_Vaginal05_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Hound",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletLloigor_Anal01"] = {
            ["id"] = "AletLloigor_Anal01",
            ["match_keys"] = {
                "AletLloigor_Anal01",
                "AletLloigor_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Lloigor",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletLloigor_Anal02"] = {
            ["id"] = "AletLloigor_Anal02",
            ["match_keys"] = {
                "AletLloigor_Anal02",
                "AletLloigor_Anal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Lloigor",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletLloigor_Vagina01"] = {
            ["id"] = "AletLloigor_Vagina01",
            ["match_keys"] = {
                "AletLloigor_Vagina01",
                "AletLloigor_Vagina01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Lloigor",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletMale_A_Foot04"] = {
            ["id"] = "AletMale_A_Foot04",
            ["match_keys"] = {
                "AletMale_A_Foot04",
                "AletMale_A_Foot04_Alet_04_nor",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Male_A",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "foot_nearest_reference",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_A_Foot05"] = {
            ["id"] = "AletMale_A_Foot05",
            ["match_keys"] = {
                "AletMale_A_Foot05",
                "AletMale_A_Foot05_Alet_04_nor",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Male_A",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "foot_nearest_reference",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_A_Foot06"] = {
            ["id"] = "AletMale_A_Foot06",
            ["match_keys"] = {
                "AletMale_A_Foot06",
                "AletMale_A_Foot06_Alet_04_nor",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Male_A",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "foot_nearest_reference",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Anal02"] = {
            ["id"] = "AletMale_Anal02",
            ["match_keys"] = {
                "AletMale_Anal02",
                "AletMale_Anal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Anal03"] = {
            ["id"] = "AletMale_Anal03",
            ["match_keys"] = {
                "AletMale_Anal03",
                "AletMale_Anal03_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Anal04"] = {
            ["id"] = "AletMale_Anal04",
            ["match_keys"] = {
                "AletMale_Anal04",
                "AletMale_Anal04_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Anal06"] = {
            ["id"] = "AletMale_Anal06",
            ["match_keys"] = {
                "AletMale_Anal06",
                "AletMale_Anal06_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Anal07"] = {
            ["id"] = "AletMale_Anal07",
            ["match_keys"] = {
                "AletMale_Anal07",
                "AletMale_Anal07_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Anus01"] = {
            ["id"] = "AletMale_Anus01",
            ["match_keys"] = {
                "AletMale_Anus01",
                "AletMale_Anus01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Foot01"] = {
            ["id"] = "AletMale_Foot01",
            ["match_keys"] = {
                "AletMale_Foot01",
                "AletMale_Foot01_Alet_04_NOR",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "foot_nearest_reference",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Foot02"] = {
            ["id"] = "AletMale_Foot02",
            ["match_keys"] = {
                "AletMale_Foot02",
                "AletMale_Foot02_Alet_04_NOR",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "foot_nearest_reference",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Foot03"] = {
            ["id"] = "AletMale_Foot03",
            ["match_keys"] = {
                "AletMale_Foot03",
                "AletMale_Foot03_Alet_04_nor",
            },
            ["category"] = "foot_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "foot_nearest_reference",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Hand01"] = {
            ["id"] = "AletMale_Hand01",
            ["match_keys"] = {
                "AletMale_Hand01",
                "AletMale_Hand01_Alet_04_nor",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "right_hand",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Hand02"] = {
            ["id"] = "AletMale_Hand02",
            ["match_keys"] = {
                "AletMale_Hand02",
                "AletMale_Hand02_Alet_04_nor",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "right_hand",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Hand03"] = {
            ["id"] = "AletMale_Hand03",
            ["match_keys"] = {
                "AletMale_Hand03",
                "AletMale_Hand03_Alet_04_nor",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "right_hand",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Mouth02"] = {
            ["id"] = "AletMale_Mouth02",
            ["match_keys"] = {
                "AletMale_Mouth02",
                "AletMale_Mouth02_Alet_04_nor",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "mouth_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vagina12"] = {
            ["id"] = "AletMale_Vagina12",
            ["match_keys"] = {
                "AletMale_Vagina12",
                "AletMale_Vagina12_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal01"] = {
            ["id"] = "AletMale_Vaginal01",
            ["match_keys"] = {
                "AletMale_Vaginal01",
                "AletMale_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal02"] = {
            ["id"] = "AletMale_Vaginal02",
            ["match_keys"] = {
                "AletMale_Vaginal02",
                "AletMale_Vaginal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal04"] = {
            ["id"] = "AletMale_Vaginal04",
            ["match_keys"] = {
                "AletMale_Vaginal04",
                "AletMale_Vaginal04_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal05"] = {
            ["id"] = "AletMale_Vaginal05",
            ["match_keys"] = {
                "AletMale_Vaginal05",
                "AletMale_Vaginal05_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal07"] = {
            ["id"] = "AletMale_Vaginal07",
            ["match_keys"] = {
                "AletMale_Vaginal07",
                "AletMale_Vaginal07_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal08"] = {
            ["id"] = "AletMale_Vaginal08",
            ["match_keys"] = {
                "AletMale_Vaginal08",
                "AletMale_Vaginal08_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal09"] = {
            ["id"] = "AletMale_Vaginal09",
            ["match_keys"] = {
                "AletMale_Vaginal09",
                "AletMale_Vaginal09_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal10"] = {
            ["id"] = "AletMale_Vaginal10",
            ["match_keys"] = {
                "AletMale_Vaginal10",
                "AletMale_Vaginal10_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal11"] = {
            ["id"] = "AletMale_Vaginal11",
            ["match_keys"] = {
                "AletMale_Vaginal11",
                "AletMale_Vaginal11_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal13"] = {
            ["id"] = "AletMale_Vaginal13",
            ["match_keys"] = {
                "AletMale_Vaginal13",
                "AletMale_Vaginal13_Alet_04NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal14"] = {
            ["id"] = "AletMale_Vaginal14",
            ["match_keys"] = {
                "AletMale_Vaginal14",
                "AletMale_Vaginal14_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal15"] = {
            ["id"] = "AletMale_Vaginal15",
            ["match_keys"] = {
                "AletMale_Vaginal15",
                "AletMale_Vaginal15_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal16"] = {
            ["id"] = "AletMale_Vaginal16",
            ["match_keys"] = {
                "AletMale_Vaginal16",
                "AletMale_Vaginal16_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMale_Vaginal17"] = {
            ["id"] = "AletMale_Vaginal17",
            ["match_keys"] = {
                "AletMale_Vaginal17",
                "AletMale_Vaginal17_Alet_04NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "vaginal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
        ["AletMaleAB_VaginalHand01"] = {
            ["id"] = "AletMaleAB_VaginalHand01",
            ["match_keys"] = {
                "AletMaleAB_VaginalHand01",
                "AletMaleAB_VaginalHand01_Alet_04_nor",
            },
            ["category"] = "hand_guided",
            ["participant_hint"] = "MaleAB",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_multi_participant_binding",
        },
        ["AletMaleAB_VaginalMouth01"] = {
            ["id"] = "AletMaleAB_VaginalMouth01",
            ["match_keys"] = {
                "AletMaleAB_VaginalMouth01",
                "AletMaleAB_VaginalMouth01_Alet_04_nor",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "MaleAB",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_multi_participant_binding",
        },
        ["AletMaleAB_VaginalMouth02"] = {
            ["id"] = "AletMaleAB_VaginalMouth02",
            ["match_keys"] = {
                "AletMaleAB_VaginalMouth02",
                "AletMaleAB_VaginalMouth02_Alet_04nor",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "MaleAB",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_multi_participant_binding",
        },
        ["AletMiGoNymph_Arse01"] = {
            ["id"] = "AletMiGoNymph_Arse01",
            ["match_keys"] = {
                "AletMiGoNymph_Arse01",
                "AletMiGoNymph_Arse01_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "MiGoNymph",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Anal01"] = {
            ["id"] = "AletScorpio_Anal01",
            ["match_keys"] = {
                "AletScorpio_Anal01",
                "AletScorpio_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Anal02"] = {
            ["id"] = "AletScorpio_Anal02",
            ["match_keys"] = {
                "AletScorpio_Anal02",
                "AletScorpio_Anal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Anal03"] = {
            ["id"] = "AletScorpio_Anal03",
            ["match_keys"] = {
                "AletScorpio_Anal03",
                "AletScorpio_Anal03_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Breast01"] = {
            ["id"] = "AletScorpio_Breast01",
            ["match_keys"] = {
                "AletScorpio_Breast01",
                "AletScorpio_Breast01_Alet_04_NOR",
            },
            ["category"] = "breast_contact",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Mouth01"] = {
            ["id"] = "AletScorpio_Mouth01",
            ["match_keys"] = {
                "AletScorpio_Mouth01",
                "AletScorpio_Mouth01_Alet_04_NOR",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Vaginal02"] = {
            ["id"] = "AletScorpio_Vaginal02",
            ["match_keys"] = {
                "AletScorpio_Vaginal02",
                "AletScorpio_Vaginal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Vaginal03"] = {
            ["id"] = "AletScorpio_Vaginal03",
            ["match_keys"] = {
                "AletScorpio_Vaginal03",
                "AletScorpio_Vaginal03_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Vaginal04"] = {
            ["id"] = "AletScorpio_Vaginal04",
            ["match_keys"] = {
                "AletScorpio_Vaginal04",
                "AletScorpio_Vaginal04_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpio_Vaginal05"] = {
            ["id"] = "AletScorpio_Vaginal05",
            ["match_keys"] = {
                "AletScorpio_Vaginal05",
                "AletScorpio_Vaginal05_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpio",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpioMale_VaginalMouth01"] = {
            ["id"] = "AletScorpioMale_VaginalMouth01",
            ["match_keys"] = {
                "AletScorpioMale_VaginalMouth01",
                "AletScorpioMale_VaginalMouth01_Alet_04_nor",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "ScorpioMale",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletScorpion_Vaginal01"] = {
            ["id"] = "AletScorpion_Vaginal01",
            ["match_keys"] = {
                "AletScorpion_Vaginal01",
                "AletScorpion_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Scorpion",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletSkorpios_Vaginal06"] = {
            ["id"] = "AletSkorpios_Vaginal06",
            ["match_keys"] = {
                "AletSkorpios_Vaginal06",
                "AletSkorpios_Vaginal06_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Skorpios",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletSylph_Anal01"] = {
            ["id"] = "AletSylph_Anal01",
            ["match_keys"] = {
                "AletSylph_Anal01",
                "AletSylph_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Sylph",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletSylph_Anal02"] = {
            ["id"] = "AletSylph_Anal02",
            ["match_keys"] = {
                "AletSylph_Anal02",
                "AletSylph_Anal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Sylph",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletSylph_Vaginal01"] = {
            ["id"] = "AletSylph_Vaginal01",
            ["match_keys"] = {
                "AletSylph_Vaginal01",
                "AletSylph_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Sylph",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletSylph_Vaginal02"] = {
            ["id"] = "AletSylph_Vaginal02",
            ["match_keys"] = {
                "AletSylph_Vaginal02",
                "AletSylph_Vaginal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Sylph",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTantacle_Breast01"] = {
            ["id"] = "AletTantacle_Breast01",
            ["match_keys"] = {
                "AletTantacle_Breast01",
                "AletTantacle_Breast01_Alet_04_NOR",
            },
            ["category"] = "breast_contact",
            ["participant_hint"] = "Tantacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTentacle_Anal01"] = {
            ["id"] = "AletTentacle_Anal01",
            ["match_keys"] = {
                "AletTentacle_Anal01",
                "AletTentacle_Anal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Tentacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTentacle_Mouth01"] = {
            ["id"] = "AletTentacle_Mouth01",
            ["match_keys"] = {
                "AletTentacle_Mouth01",
                "AletTentacle_Mouth01_Alet_04_NOR",
            },
            ["category"] = "mouth_guided",
            ["participant_hint"] = "Tentacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTentacle_Vaginal01"] = {
            ["id"] = "AletTentacle_Vaginal01",
            ["match_keys"] = {
                "AletTentacle_Vaginal01",
                "AletTentacle_Vaginal01_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Tentacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTentacle_Vaginal02"] = {
            ["id"] = "AletTentacle_Vaginal02",
            ["match_keys"] = {
                "AletTentacle_Vaginal02",
                "AletTentacle_Vaginal02_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Tentacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTentacle_Vaginal03"] = {
            ["id"] = "AletTentacle_Vaginal03",
            ["match_keys"] = {
                "AletTentacle_Vaginal03",
                "AletTentacle_Vaginal03_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Tentacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletTentacle_Vaginal06"] = {
            ["id"] = "AletTentacle_Vaginal06",
            ["match_keys"] = {
                "AletTentacle_Vaginal06",
                "AletTentacle_Vaginal06_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Tentacle",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["AletYith_Anal02"] = {
            ["id"] = "AletYith_Anal02",
            ["match_keys"] = {
                "AletYith_Anal02",
                "AletYith_Anal02_Alet_04_nor",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Yith",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
            },
            ["status"] = "awaiting_partner_skeleton",
        },
        ["JuziAlet_Vaginal20231107_TimingX"] = {
            ["id"] = "JuziAlet_Vaginal20231107_TimingX",
            ["match_keys"] = {
                "JuziAlet_Vaginal20231107_TimingX",
                "JuziAlet_Vaginal20231107_TimingX_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Juzi_Vaginal20231107_TimingX",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "juzi-humanoid",
            },
            ["status"] = "catalog_match_only",
        },
        ["MaleAlet_Anal05"] = {
            ["id"] = "MaleAlet_Anal05",
            ["match_keys"] = {
                "MaleAlet_Anal05",
                "MaleAlet_Anal05_Alet_04_NOR",
            },
            ["category"] = "penetration",
            ["participant_hint"] = "Male_Anal05",
            ["roles"] = {
                ["primary"] = "alet-humanoid",
                ["partner"] = "male-b-humanoid",
            },
            ["status"] = "enabled_for_simulation_validation",
            ["geometry"] = {
                ["reference_role"] = "partner",
                ["reference_origin_semantic"] = "primary_origin",
                ["reference_tip_semantic"] = "primary_tip",
                ["target_role"] = "primary",
                ["target_semantic"] = "anal_origin",
                ["max_pair_distance_cm"] = 100,
            },
        },
    },
}
